server:
    port: 5001

app:
    frontend:
        url: ${FRONTEND_URL:http://localhost:5173}

spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: auth-service

    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 2
            idle-timeout: 600000
            max-lifetime: 600000
            connection-timeout: 30000

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID:placeholder-google-id}
                        client-secret: ${GOOGLE_CLIENT_SECRET:placeholder-google-secret}
                        scope: profile, email
                    github:
                        client-id: ${GITHUB_CLIENT_ID:placeholder-github-id}
                        client-secret: ${GITHUB_CLIENT_SECRET:placeholder-github-secret}
                        scope: user:email, read:user


    data:
        redis:
            host: ${REDIS_HOST:localhost}
            port: ${REDIS_PORT:6379}

    kafka:
        bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    jwt:
        secret: ${JWT_SECRET:supersecretkeythatisverylongandsecurebecausejwtneedsit}
        expiration: 604800000

management:
    endpoints:
        web:
            exposure:
                include: health, prometheus
    endpoint:
        health:
            show-details: always